package org.example.dao;

import org.apache.ibatis.annotations.Param;
import org.example.dataobject.ItemDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    int insert(ItemDO record);

    List<ItemDO> listItem();

    int increaseSales(@Param("amount")Integer amount,@Param("itemid")Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    int updateByPrimaryKey(ItemDO record);
}