package org.example.dao;

import org.example.dataobject.UserPassword;
import org.springframework.stereotype.Repository;

@Repository
public interface UserPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 15 15:58:50 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 15 15:58:50 CST 2021
     */
    int insert(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 15 15:58:50 CST 2021
     */
    int insertSelective(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 15 15:58:50 CST 2021
     */
    UserPassword selectByPrimaryKey(Integer id);

    UserPassword selectByUserId(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 15 15:58:50 CST 2021
     */
    int updateByPrimaryKeySelective(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Jun 15 15:58:50 CST 2021
     */
    int updateByPrimaryKey(UserPassword record);
}