package org.example.dataobject;

public class ItemStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.id
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.item_id
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.id
     *
     * @return the value of stock_info.id
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.id
     *
     * @param id the value for stock_info.id
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock
     *
     * @return the value of stock_info.stock
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.stock
     *
     * @param stock the value for stock_info.stock
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.item_id
     *
     * @return the value of stock_info.item_id
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_info.item_id
     *
     * @param itemId the value for stock_info.item_id
     *
     * @mbg.generated Wed Jun 16 15:24:11 CST 2021
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}